/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

import java.sql.*;
import java.util.Enumeration;
import java.util.Properties;

import com.mysql.cj.conf.DatabaseUrlContainer;

public class App {

    public static void main(String[] args) 
    {
        new App().initializeDBState();
    }

    public static final String dbHostDomain = "localhost";
    public static final int port            = 3306; 
    public Connection dbConnection;

    public void initializeDBState()
    {
        // Try connecting to the database. First, establish a Properties object for the connection.
        Properties connectionProperties = new Properties();
        connectionProperties.put("user", "root");
        connectionProperties.put("password", "fall2022se6329project");

        // Create a URL string to identify the location of the server.
        int portNumber  = 3306;
        String host     = "localhost";

        StringBuilder urlStringBuilder = new StringBuilder();
        urlStringBuilder.append("jdbc:mysql://");                // Specify protocol
        urlStringBuilder.append(host);                               // Specify server name
        urlStringBuilder.append(":");
        urlStringBuilder.append(portNumber);                         // Specify port number
        urlStringBuilder.append("/");
        String urlString = urlStringBuilder.toString();

        // Establish a connection to the MYSQL server
        Connection dbConnection_ = null;
        try
        {
            dbConnection_ = DriverManager.getConnection(urlString, connectionProperties);
        }
        catch(SQLException ex)
        {
            ex.printStackTrace();
        }

        dbConnection = dbConnection_;

        try(Statement statement = dbConnection.createStatement())
        {
            // Delete all tuples from all tables
            statement.execute("DELETE FROM cometbooks.message;");
            statement.execute("DELETE FROM cometbooks.wishlist;");
            statement.execute("DELETE FROM cometbooks.transaction;");
            statement.execute("DELETE FROM cometbooks.listing;");
            statement.execute("DELETE FROM cometbooks.book;");

            // Add some example tuples to each table
            statement.execute("INSERT INTO cometbooks.book VALUES (12345, 'Test Title', 'Nathan Beck', 1, 1999)");
            statement.execute("INSERT INTO cometbooks.book VALUES (12346, 'Test Title 2', 'Dhruvi Shah', 2, 2000)");
            statement.execute("INSERT INTO cometbooks.book VALUES (12347, 'Test Title 3', 'Tirth Mehra', 3, 2001)");
            
            statement.execute("INSERT INTO cometbooks.listing VALUES (1, 12345, 'Like New', 12.50, 'Only a smudge on the cover', 0, 'abc123456')");
            statement.execute("INSERT INTO cometbooks.listing VALUES (2, 12345, 'Poor', 1.50, 'Please just take this off me', 0, 'zyx654321')");
            statement.execute("INSERT INTO cometbooks.listing VALUES (3, 12346, 'New', 21.50, 'Still in its plastic wrap', 0, 'abc123456')");

            statement.execute("INSERT INTO cometbooks.transaction VALUES (1, 1, '', 'nab170130')");
            statement.execute("INSERT INTO cometbooks.transaction VALUES (2, 2, '', 'nab170131')");
            statement.execute("INSERT INTO cometbooks.transaction VALUES (3, 3, '', 'nab170132')");

            statement.execute("INSERT INTO cometbooks.wishlist VALUES ('nab170130', 12345)");
            statement.execute("INSERT INTO cometbooks.wishlist VALUES ('nab170130', 12346)");
            statement.execute("INSERT INTO cometbooks.wishlist VALUES ('nab170131', 12345)");

            statement.execute("INSERT INTO cometbooks.message VALUES (1, 'nab170130', 1, 'Hey, I want your book.')");
            statement.execute("INSERT INTO cometbooks.message VALUES (1, 'abc123456', 2, 'Okay, sure.')");
            statement.execute("INSERT INTO cometbooks.message VALUES (2, 'nab170131', 1, 'Hey, can I have your book?')");
            statement.execute("INSERT INTO cometbooks.message VALUES (2, 'nab170131', 10, 'Hello?')");
        }
        catch(SQLException ex)
        {
            ex.printStackTrace();
        }
    }
}
